# Generated by Django 4.0.8 on 2023-01-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='resources',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='output',
            field=models.JSONField(null=True),
        ),
    ]
