# Generated by Django 4.0.8 on 2023-01-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_environment_resources_alter_environment_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='resources',
            new_name='deployment_resources',
        ),
    ]
