# Generated by Django 4.0.8 on 2023-01-12 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectenvironment'),
        ('services', '0003_rename_resources_environment_deployment_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='name',
        ),
        migrations.AddField(
            model_name='environment',
            name='project_env',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.projectenvironment'),
            preserve_default=False,
        ),
    ]
