# Generated by Django 4.1.4 on 2022-12-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=128)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=150, null=True)),
                ("last_name", models.CharField(default="", max_length=150, null=True)),
                ("ad_username", models.CharField(max_length=128, null=True)),
                ("github_username", models.CharField(max_length=128, null=True)),
                ("github_token", models.CharField(max_length=128, null=True)),
                ("google_access_token", models.CharField(max_length=2048, null=True)),
                ("google_refresh_token", models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.DeleteModel(name="Destination",),
    ]
