# Generated by Django 4.1.4 on 2022-12-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_authtoken_user_delete_destination"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="projects",
            field=models.ManyToManyField(
                through="projects.ProjectAccess", to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="authtoken",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
            ),
        ),
    ]
