# Generated by Django 4.0.8 on 2022-12-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='metadata',
            new_name='metadata_values',
        ),
    ]
