# Generated by Django 4.0.8 on 2022-12-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('resources', '0002_rename_metadata_resource_metadata_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='enviornment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.environment'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
