# Generated by Django 4.0.8 on 2022-12-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_enviornment_alter_resource_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='enviornment',
            new_name='environment',
        ),
    ]
