# Generated by Django 4.0.8 on 2023-01-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resource_metadata_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
